### ISSUE TITLE
USER STORY: Leaving Comments

### ISSUE THREAD

**Issue by Tossan99** [Tossan99/osrs-tips#12]
As a **registered user** I can **leave comments on posts** so that **I can share my opinion on a post**

## Acceptance Criteria
- Users can leave comments on posts
- Users have full access to edit and delete their comments
- Submitted comments needs admin approval

## Tasks
- [x] Create a "leave comment" feature for registered user
- [x] Give registered user full crud over their own comments
- [x] Implement a feature that withholds comments untill approved by an admin
