### ISSUE TITLE
USER STORY: Admin Control Over User Accounts

### ISSUE THREAD

**Issue by Tossan99** [Tossan99/osrs-tips#13]
As an **admin** I have**full control over users accounts** so that **I have the ability to approve and ban users.**

## Acceptance Criteria
- Admins can access a dedicated admin page
- Admins can view a list of all user accounts
- Admins can approve new user registrations
- Admins can ban users

## Tasks
- [ ] Create a dedicated admin page
- [ ] Implement a user management section to the page
- [ ] Implement a feature to approve new users
- [ ] Implement a feature to ban users
