### ISSUE TITLE
USER STORY: User Navigation

### ISSUE THREAD

**Issue by Tossan99** [Tossan99/osrs-tips#7]
As a **new user** I can **easily navigate the website to find content that interests me** so that **I can take part of the information I'm looking for.**

## Acceptance Criteria
- Users can easily find the main navigation menu
- There is a "category" menu for different topics
- Posts can be sorted by date and likes

## Tasks
- [ ] Create and implement a clear and prominent navigation menu
- [ ] Create a category menu that filters posts by different topics
- [ ] Create a feature that sors posts by date or likes
