### ISSUE TITLE
USER STORY: Personalized Profile

### ISSUE THREAD

**Issue by Tossan99** [Tossan99/osrs-tips#8]
As a **registered user** I can **personalize my profile** so that **i can have a stronger presence on the website.**

## Acceptance Criteria
- Registered user can add a profile picture
- Registered user can add and edit their bio
- Registered user can save posts to their profile page

## Tasks
- [ ] Add a feature for users to uppload an image to their profile page
- [ ] Add a feature for users to write a bio for their profile page
- [ ] Add a feature for users to save posts to their profile page
