### ISSUE TITLE
USER STORY: Search bar

### ISSUE THREAD

**Issue by Tossan99** [Tossan99/osrs-tips#9]
As a **user** I can **search for a specific post or topic** so that **I spend less time looking for a the information i need.**

## Acceptance Criteria
- Users can access a search bar from relevant pages on the blog
- The user is redirected to a page with posts containing the searched words

## Tasks
- [ ] Implement a search bar in an easily accessible place
- [ ] Redirect the user to a new page after submitting the search
- [ ] On that page, implement a filter that only displays post with words that matches the users search
